// macOS reads the Dock/Cmd+Tab label for a running app from its bundle's
// Info.plist (CFBundleName/CFBundleDisplayName), not from anything
// app.setName() can change at runtime. In dev, that bundle is the generic
// Electron.app shipped inside node_modules, so it shows "Electron" in the
// Dock unless we rename it here. This has no effect on the packaged app,
// whose Info.plist is generated by electron-builder from productName.
//
// Editing the plist alone isn't enough: LaunchServices caches the bundle's
// name keyed off the .app folder's own mtime, which editing a file nested
// inside Contents/ doesn't change. So after editing, we touch the bundle
// and force LaunchServices to re-register it.
import { execFileSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { resolve } from 'node:path'

if (process.platform === 'darwin') {
  const appName = 'Saved Variables Manager'
  const bundlePath = resolve('node_modules/electron/dist/Electron.app')
  const plistPath = resolve(bundlePath, 'Contents/Info.plist')

  if (existsSync(plistPath)) {
    for (const key of ['CFBundleName', 'CFBundleDisplayName']) {
      try {
        execFileSync('plutil', ['-replace', key, '-string', appName, plistPath])
      } catch {
        execFileSync('plutil', ['-insert', key, '-string', appName, plistPath])
      }
    }

    execFileSync('touch', [bundlePath])
    execFileSync(
      '/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister',
      ['-f', bundlePath]
    )
  }
}
