import type { LuaValue } from '@shared/luaTypes'

/**
 * Minimal recursive-descent parser for the restricted Lua subset WoW addons write to
 * SavedVariables files: a single `Identifier = TableConstructor` assignment, where every
 * value is a nested table, string, number, boolean, or nil. There are no operators,
 * function calls, or control flow in this grammar - it is machine-generated by Lua's/Ace3's
 * table serializer, never hand-written or executed as a program.
 */

const WHITESPACE = new Set([' ', '\t', '\r', '\n'])

export class LuaParseError extends Error {
  constructor(
    message: string,
    public readonly offset: number,
    public readonly line: number
  ) {
    super(`${message} (line ${line}, offset ${offset})`)
    this.name = 'LuaParseError'
  }
}

export interface ParsedLuaAssignment {
  varName: string
  value: LuaValue
}

export function parseLuaAssignment(source: string): ParsedLuaAssignment {
  const parser = new Parser(source)
  return parser.parseAssignment()
}

class Parser {
  private pos = 0
  private line = 1

  constructor(private readonly src: string) {}

  parseAssignment(): ParsedLuaAssignment {
    this.skipTrivia()
    const varName = this.readIdentifier()
    this.skipTrivia()
    this.expectChar('=')
    this.skipTrivia()
    const value = this.parseValue()
    return { varName, value }
  }

  private parseValue(): LuaValue {
    this.skipTrivia()
    const c = this.peek()
    if (c === '{') return this.parseTable()
    if (c === '"' || c === "'") return this.parseString(c)
    if (c === '-' || this.isDigit(c)) return this.parseNumber()
    if (this.matchKeyword('nil')) return null
    if (this.matchKeyword('true')) return true
    if (this.matchKeyword('false')) return false
    throw this.error(`Unexpected character '${c}' while parsing a value`)
  }

  private parseTable(): LuaValue {
    this.expectChar('{')
    this.skipTrivia()

    const obj: Record<string, LuaValue> = {}
    const arr: LuaValue[] = []
    let sawKeyedField = false
    let sawPositionalField = false
    let nextIndex = 1

    while (this.peek() !== '}') {
      if (this.pos >= this.src.length) throw this.error('Unexpected end of input inside table')

      if (this.peek() === '[') {
        // ["key"] = value
        this.expectChar('[')
        this.skipTrivia()
        const keyChar = this.peek()
        let key: string
        if (keyChar === '"' || keyChar === "'") {
          key = this.parseString(keyChar) as string
        } else {
          // Numeric or bare keys inside brackets, e.g. [1] = value - not seen in practice
          // but handled defensively.
          const numKey = this.parseNumber()
          key = String(numKey)
        }
        this.skipTrivia()
        this.expectChar(']')
        this.skipTrivia()
        this.expectChar('=')
        this.skipTrivia()
        const value = this.parseValue()
        obj[key] = value
        sawKeyedField = true
      } else {
        // Bare positional value, e.g. `1,` inside `color = {1,1,1,1}`
        const value = this.parseValue()
        arr[nextIndex - 1] = value
        nextIndex += 1
        sawPositionalField = true
      }

      this.skipTrivia()
      if (this.peek() === ',' || this.peek() === ';') {
        this.advance()
        this.skipTrivia()
      } else if (this.peek() !== '}') {
        throw this.error(`Expected ',' or '}' inside table, found '${this.peek()}'`)
      }
    }
    this.expectChar('}')

    if (sawPositionalField && !sawKeyedField) return arr
    if (sawKeyedField && !sawPositionalField) return obj
    if (!sawKeyedField && !sawPositionalField) return {} // empty table, treat as empty object
    // Mixed table (not seen in practice, handled defensively): fold positional entries
    // into the object under their 1-based numeric-string index.
    arr.forEach((v, i) => {
      if (v !== undefined) obj[String(i + 1)] = v
    })
    return obj
  }

  private parseString(quote: string): string {
    this.expectChar(quote)
    const start = this.pos
    let out: string | null = null // lazily allocated only if an escape is found
    let segmentStart = start

    while (true) {
      if (this.pos >= this.src.length) throw this.error('Unterminated string literal')
      const c = this.src[this.pos]
      if (c === '\\') {
        if (out === null) out = ''
        out += this.src.slice(segmentStart, this.pos)
        out += this.decodeEscape()
        segmentStart = this.pos
        continue
      }
      if (c === quote) break
      if (c === '\n') this.line += 1
      this.pos += 1
    }

    const raw = this.src.slice(segmentStart, this.pos)
    this.expectChar(quote)
    return out === null ? raw : out + raw
  }

  /** Called with `this.pos` at the backslash; consumes the escape and returns its value. */
  private decodeEscape(): string {
    this.pos += 1 // consume '\\'
    const c = this.src[this.pos]
    if (c === undefined) throw this.error('Unterminated escape sequence')
    switch (c) {
      case 'n':
        this.pos += 1
        return '\n'
      case 't':
        this.pos += 1
        return '\t'
      case 'r':
        this.pos += 1
        return '\r'
      case 'a':
        this.pos += 1
        return '\x07'
      case 'b':
        this.pos += 1
        return '\b'
      case 'f':
        this.pos += 1
        return '\f'
      case 'v':
        this.pos += 1
        return '\v'
      case '\\':
      case '"':
      case "'":
        this.pos += 1
        return c
      case '\n':
        this.pos += 1
        this.line += 1
        return '\n'
      default:
        if (c >= '0' && c <= '9') {
          // \ddd decimal byte escape (up to 3 digits)
          let digits = ''
          while (digits.length < 3 && this.isDigit(this.src[this.pos])) {
            digits += this.src[this.pos]
            this.pos += 1
          }
          return String.fromCharCode(parseInt(digits, 10))
        }
        // Unknown escape: keep the character as-is (defensive, shouldn't happen in practice).
        this.pos += 1
        return c
    }
  }

  private parseNumber(): number {
    const start = this.pos
    if (this.peek() === '-') this.pos += 1
    while (this.isDigit(this.peek())) this.pos += 1
    if (this.peek() === '.') {
      this.pos += 1
      while (this.isDigit(this.peek())) this.pos += 1
    }
    if (this.peek() === 'e' || this.peek() === 'E') {
      this.pos += 1
      if (this.peek() === '+' || this.peek() === '-') this.pos += 1
      while (this.isDigit(this.peek())) this.pos += 1
    }
    const text = this.src.slice(start, this.pos)
    if (text.length === 0 || text === '-') throw this.error('Expected a number')
    return Number(text)
  }

  private isDigit(c: string | undefined): boolean {
    return c !== undefined && c >= '0' && c <= '9'
  }

  private matchKeyword(keyword: string): boolean {
    if (this.src.startsWith(keyword, this.pos)) {
      const after = this.src[this.pos + keyword.length]
      if (after === undefined || !/[A-Za-z0-9_]/.test(after)) {
        this.pos += keyword.length
        return true
      }
    }
    return false
  }

  private readIdentifier(): string {
    const start = this.pos
    while (/[A-Za-z0-9_]/.test(this.peek() ?? '')) this.pos += 1
    if (this.pos === start) throw this.error('Expected an identifier')
    return this.src.slice(start, this.pos)
  }

  private skipTrivia(): void {
    while (this.pos < this.src.length) {
      const c = this.src[this.pos]
      if (c !== undefined && WHITESPACE.has(c)) {
        if (c === '\n') this.line += 1
        this.pos += 1
        continue
      }
      if (c === '-' && this.src[this.pos + 1] === '-') {
        this.pos += 2
        if (this.src[this.pos] === '[' && this.src[this.pos + 1] === '[') {
          this.pos += 2
          const end = this.src.indexOf(']]', this.pos)
          const stop = end === -1 ? this.src.length : end + 2
          for (let i = this.pos; i < stop; i++) if (this.src[i] === '\n') this.line += 1
          this.pos = stop
        } else {
          const end = this.src.indexOf('\n', this.pos)
          this.pos = end === -1 ? this.src.length : end
        }
        continue
      }
      break
    }
  }

  private peek(): string | undefined {
    return this.src[this.pos]
  }

  private advance(): string {
    const c = this.src[this.pos] ?? ''
    this.pos += 1
    return c
  }

  private expectChar(expected: string): void {
    if (this.src[this.pos] !== expected) {
      throw this.error(`Expected '${expected}', found '${this.src[this.pos]}'`)
    }
    this.pos += 1
  }

  private error(message: string): LuaParseError {
    return new LuaParseError(message, this.pos, this.line)
  }
}
